### ISSUE TITLE
Execution Parameters Error

### ISSUE THREAD

**Issue by Mohsen-taherzadeh** [DualSPHysics/DesignSPHysics#105]
Dear users,
Hello
When I'm going to execute my parameters, this error appears after I click on the execution parameters.
DesignSPHysics encountered an error. Please report the developer the following details:

DesignSPHysics version: 0.6.0.1911-07-2

Exception type: <class 'PermissionError'>

Exception value: [Errno 13] Permission denied: 'C:\\Program Files\\FreeCAD 0.19\\Mod\\DesignSPHysics-0.6.0.1911-07-2\\mod/lang/english.json'

Traceback:

  File "C:/Program Files/FreeCAD 0.19/Mod/DesignSPHysics-0.6.0.1911-07-2\mod\widgets\dock\dock_configuration_widget.py", line 61, in on_execparams_button_presed

    ExecutionParametersDialog(parent=get_fc_main_window())

  File "C:/Program Files/FreeCAD 0.19/Mod/DesignSPHysics-0.6.0.1911-07-2\mod\widgets\execution_parameters_dialog.py", line 424, in __init__

    self.period_x_inc_y_input.set_help_text(__(HELP_YINCREMENTX))

  File "C:/Program Files/FreeCAD 0.19/Mod/DesignSPHysics-0.6.0.1911-07-2\mod\translation_tools.py", line 35, in __

    with open(filename, "w", encoding="utf8") as f:

Have you been had any experience?

best regards

**Comment by zlotny** [comment]
Hi there. This error is caused because of the way you installed DesignSPHysics on your Windows machine. In regular use, FreeCAD should have installed the macro on a directory like C:\AppData\Local or something along the way, however yours is installed on C:\Program Files, which is a directory with no write permission for regular users.

I don't know if this is caused by installing the Macro while running FreeCAD as an administrator or if you manually installed the macro there. However I have 2 relatively easy solutions:

1 - Run FreeCAD as administrator. This is not the best solution as it lets the code modify important files and whatnot in your system, but it can get you going.

2 - Uninstall the macro (probably while running FreeCAD as administrator, if you installed it this way) and then reinstall DesignSPHyiscs while running FreeCAD as a regular user.

Hope this helps.

**Comment by Mohsen-taherzadeh** [comment]
Thanks dear zlotny.
my problem was solved with your guidance.
