### ISSUE TITLE
How to choose the specific GPU for multi GPU?

### ISSUE THREAD

**Issue by yoyokal** [DualSPHysics/DesignSPHysics#108]
I have two GPUs, #0 Tesla K20c and #1 Quadro K2200. DesignSPHysics looks like always use default GPU, i.e. Tesla K20c. Because K20c sometimes runs machine learning, I need to choose K2200 as the default GPU. How can I choose the second GPU in a multi GPU system in DesignSPHysics?

**Comment by zlotny** [comment]
Hi there. Due to not being a common case to have 2 gpu's DesignSPHysics does not have an specific option or button for it. However you can indicate the GPU you want to use via "Additional Parameters", like this:

![image](https://user-images.githubusercontent.com/6155245/152510182-fe8e2b30-cf6d-4479-88fd-13dafe567999.png)

I believe DualSPHyiscs tries to choose the most capable GPU by default, so I'm not sure what index will be the K2200 in your case but you can try with `-gpu:0` and `-gpu:1` to find out.

Hope that helps!

**Comment by yoyokal** [comment]
> Hi there. Due to not being a common case to have 2 gpu's DesignSPHysics does not have an specific option or button for it. However you can indicate the GPU you want to use via "Additional Parameters", like this:
> 
> ![image](https://user-images.githubusercontent.com/6155245/152510182-fe8e2b30-cf6d-4479-88fd-13dafe567999.png)
> 
> I believe DualSPHyiscs tries to choose the most capable GPU by default, so I'm not sure what index will be the K2200 in your case but you can try with `-gpu:0` and `-gpu:1` to find out.
> 
> Hope that helps!

**Comment by yoyokal** [comment]
Dear Sir, it works. My K2200 is device #1, so I'm using -gpu:1, the DesignSPHysics definitely using my K2200. I checked using GPU-Z and there is GPU load. Thank you so much!
