### ISSUE TITLE
Import Porous media

### ISSUE THREAD

**Issue by hmtylcnky** [DualSPHysics/DesignSPHysics#126]
Hi,

When I import porous media as STL file generated from Blender or even if I create in the model Freecad, the simulation does not recognize voids or gaps between objects. It recognize as solid face. 

I also tried making seperate component for each object but still it is same.

It is supposed that fluid particles go through between objects, but not.

I couldn't understand where I am doing mistakes or what's the problem.
![model](https://user-images.githubusercontent.com/50395098/205104957-b63519d5-7f46-4d14-b698-ace7c6ad0989.JPG)
![Output_paraview](https://user-images.githubusercontent.com/50395098/205104960-79fcfdae-d72c-4d00-b359-b0ee134fdbec.JPG)

Thanks

**Comment by imestevez** [comment]
Hello, this happens because you are using the Dynamic Boundary Conditions (DBC). When you use this method there is a gap between the fluid and the boundary particles so, the fluid does not see the voids between the solid objects. To deal with this issue you have to keep a higher separation between each object or use the modified DBC (mDBC). Here you can find some information about this topic: https://github.com/DualSPHysics/DualSPHysics/wiki/3.-SPH-formulation#38-boundary-conditions
