### ISSUE TITLE
No fluid particles were created in the defined domain

### ISSUE THREAD

**Issue by haidixuanfeng** [DualSPHysics/DesignSPHysics#161]
Hello, I have defined the fluid and its properties when using DesignSPHysics, but the following warning still appears, 
       No fluid particles were created in the defined domain
which prevents simulation. I would like to know the reason, or do you have instructions for using this software, precautions, and source code for tools such as GenCase?

**Comment by imestevez** [comment]
It depends on the type of object you are using to create fluid particles. In case you are using `add fillbox` you have to make sure that the `FillLimit` and the `FillPoint` are within the `Case Limits` domain. Also, the `FillPoint` should be placed in a position free of any other objects, otherwise it will not create any fluid particles.

There is a set of tutorials explaining how to set up various cases and you will see different ways to generate fluid particles: https://www.youtube.com/playlist?list=PLwaIMU-iIzj0LXtoZMGFWMnKOSWynI6XK
