### ISSUE TITLE
 different phases from the beginning 

### ISSUE THREAD

**Issue by GiuliaClai** [DualSPHysics/DesignSPHysics#204]
I'm going back to ask for help. I was able to get a little ahead, but I have a question. I should have 2 fluids in different phases right from the beginning and therefore also with different viscosities. in "Execution Parameters" there is the possibility of putting a single viscosity and in the definitions of the various parts of the model I can define the material only for Bound and not for Fluid. Is there the possibility of using 2 different fluids and in different phases? How should I proceed? Thanks a lot

**Comment by aepoc** [comment]
The freecad macro does not support multiphase (two fluids in one simulation).  It is my understanding that this can only be done via editing an XML - using the full DualSPHysics package.  It is also my understanding that the multiphase code hasn't been updated since version 4 so it may not include some of the current tools/features.  If you download the full package, you can find some examples for mphase_liquidgas and mphase_nnewtonian in the examples folder.  

Don't let the XML editing scare you...  I delayed editing the XMLs for a long time but once you start working with them, you'll realize that there are many more tools and you can do much more with the code.  For the most part, everything you need will be in at least one of the examples and editing the XMLs is essentially copy and paste...  you add the parts you need for your case and adjust to the correct values and you can use a batch file to run gencase, simulation, and post processing.  I still use the freecad macro to import STLs and move/orient them to the correct positions.  Then I use the casedef XML as a jumping off point for using the full code.  Freecad is also useful for me to determine coordinates for measure points when I'm using imported geometry.

Best

**Comment by imestevez** [comment]
Thank you @aepoc for your answer. The use of the multiphase solver is not included in DesignSPHysics. However, you can download the full package of DualSPHysics (available at https://dual.sphysics.org/downloads/), which includes all the features implemented in the SPH solver using XMLs as input configuration files
