### ISSUE TITLE
Simulating breaking wave in deep water

### ISSUE THREAD

**Issue by WangJJ666** [DualSPHysics/DesignSPHysics#36]
Hello, I have a question when using DualSPHysics. Can this method simulate the breaking wave in deep water? Does anyone know?

**Comment by zlotny** [comment]
Hi there! I'm not an expert on the matter but I think that question is more related to DualSPHysics. You'll probably get more answers and general knowledge in the DualSPHysics forums: https://forums.dual.sphysics.org/

For further reference (and because I know the names of these tools are a bit confusing...):
 - DualSPHysics: SPH Solver suite, in which you'll find GenCase, the solver (DualSPHysics) and the post-processing tools (PartVTK, etc). Github page: https://github.com/DualSPHysics/DualSPHysics
 - DesignSPHysics: The graphical user interface to use DualSPHysics more easily, which is this repository (https://github.com/DualSPHysics/DesignSPHysics/)

I'll leave this open but as far as I know not many people look at this issues besides me, as they usually are strictly related to errors on the graphical user interface code.

**Comment by WangJJ666** [comment]
Thank you so much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Andrés Vieira"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月16日(星期一) 下午4:31
收件人:&nbsp;"DualSPHysics/DesignSPHysics"<DesignSPHysics@noreply.github.com&gt;;
抄送:&nbsp;"王佳静"<1175981439@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DualSPHysics/DesignSPHysics] Simulating breaking wave in deep water (#36)




Hi there! I'm not an expert on the matter but I think that question is more related to DualSPHysics. You'll probably get more answers and general knowledge in the DualSPHysics forums: https://forums.dual.sphysics.org/
 
For further reference (and because I know the names of these tools are a bit confusing...):
  
DualSPHysics: SPH Solver suite, in which you'll find GenCase, the solver (DualSPHysics) and the post-processing tools (PartVTK, etc). Github page: https://github.com/DualSPHysics/DualSPHysics
 
DesignSPHysics: The graphical user interface to use DualSPHysics more easily, which is this repository (https://github.com/DualSPHysics/DesignSPHysics/)
  
I'll leave this open but as far as I know not many people look at this issues besides me, as they usually are strictly related to errors on the graphical user interface code.

**Comment by zlotny** [comment]
Closing as it appears to be solved.
