### ISSUE TITLE
Issue creating multiple cylinders - orientations change.

### ISSUE THREAD

**Issue by LonelyCat124** [DualSPHysics/DesignSPHysics#40]
Hi,

I'm trying to use FreeCAD to create a cylindrical vessel with a cylinder of fluid inside (eventually motion will be added, but i want the steady state working first).

In freeCAD I created two cylinders, one of Bound type with fill mode Face, and one of Fluid type with fill mode solid:
![image](https://user-images.githubusercontent.com/3043914/72362171-951a5700-36ea-11ea-90a2-1e6981b53fee.png)

When I output this case, and Run GenCase, and then import the resulting _All.vtk to paraview (or attempt to run through DualSPHysics) I get this:
![image](https://user-images.githubusercontent.com/3043914/72362333-e4f91e00-36ea-11ea-86eb-d7ba25b327b8.png)

The XML that is output however looks sensible to me (just the snippet to define the structure here):
```
        <geometry>
            <definition dp="0.0005" comment="Initial inter-particle distance" units_comment="metres (m)">
                <pointmin x="-0.05" y="-0.05" z="-0.05" />
                <pointmax x="0.25" y="0.25" z="0.34" />
            </definition>
            <commands>
                <mainlist>
                <setshapemode>actual | dp | bound</setshapemode>
                <setmkbound mk="0"/>
                <setdrawmode mode="face"/>
                <drawcylinder radius="0.04" objname="Container">
                    <point x="0.05" y="0.05" z="0.0" />
                    <point x="0" y="0" z="0.08" />
                </drawcylinder>
                <setmkfluid mk="0"/>
                <setdrawmode mode="full"/>
                <drawcylinder radius="0.04" objname="Water">
                    <point x="0.05" y="0.05" z="0.0" />
                    <point x="0" y="0" z="0.03" />
                </drawcylinder>
                <shapeout file="" />
                </mainlist>
            </commands>
        </geometry>
```

I also get a similar weird cylinder result if I run DualSPHysics to run a step, dump a csv and plot the csv using python.
I also tried making both cylinders with drawmode=full or other options and that made no difference to how they were positioned.

Any ideas what could be happening?

**Comment by zlotny** [comment]
I took a look on the problem and it is definitely a bug. The XML that should generate from a cylinder must have the x and y coordinates of the second point strictly equal to the ones of the first point (base).

As you can see your cylinders start at 0.05 on the XML but end at 0 on the X and Y coordinates, that's why they're skewed. I didn't find and error on this because I probably tested it on the origin point where the cylinder spawns by default in FreeCAD :sweat_smile: 

As you can see the template that generates the cylinders doesn't even had a replacement value on the second point, only the height, and it's fixed at x=0 and y=0.
```
<drawcylinder radius="{radius}" objname="{label}">
    <point x="{pos[0]}" y="{pos[1]}" z="{pos[2]}" />
    <point x="0" y="0" z="{height}" />
</drawcylinder>
```

Thanks for reporting the issue! I'll fix it right away and update it on master so everyone can update.

**Comment by zlotny** [comment]
It is fixed now (on commit 845538c32b3dad9a9d493a056391d1dcce16ce7d) so you can update en retry now.

However I advise you not to fill the cylinder that way. I would use a Fillbox delimited to the height you want on the cylinder and with the fill point inside of the container. I say that because of the way GenCase produced the geometry, as if the DP is too low you may have holes on your outer shell.

However, I hope this is solved :) Closing the issue.

**Comment by LonelyCat124** [comment]
Hi - this solves the cylinder issue thanks - could you expand/is there a tutorial explaining how the Fillbox works - the one I tried gave me:
```
<setmkbound mk="0" />
<setdrawmode mode="face /> 
<drawcylinder radius="0.04" objname="Container">
    <point x="0.05" y="0.05" z="0.0 />
    <point x="0.05" y="0.05" z="0.08 />
</drawcylinder>
<setmkfluid mk="0" />
<fillbox x="0.05 y="0.05" z="0.02" objname="FillBox">
    <modefill>void</modefill>
    <point x="0" y="0" z="0" />
    <size x="0.1" y="0.1" z="0.02" />
</fillbox>
```
didn't result in the creation of any fluid when gencase was run on the geometry, though my guess on how fillbox works the fillbox definitely overlaps the volume inside the container. Any other pointers would be appreciated.

**Comment by zlotny** [comment]
Hi there. So the fillbox basically "fills" a finite area that you define (a box) starting from a point. It also ends filling particles once it reaches a boundary. Also, it fills different types of particles: bound, fluid and void.

In your case the filling point is probably outside your cylinder and the size of the box does not reach the appropriate size to work. 

In your case you want to achieve something like this, I think:
![image](https://user-images.githubusercontent.com/6155245/72506213-c35e7a80-3841-11ea-8cd7-b7a49f98e581.png)

So for that the fillbox should look like that:
![image](https://user-images.githubusercontent.com/6155245/72506252-d4a78700-3841-11ea-98c9-c26223582a7a.png)

Taking your example, this would be a working solution:

```
<setmkbound mk="0" />
<setdrawmode mode="face /> 
<drawcylinder radius="0.04" objname="Container">
    <point x="0.05" y="0.05" z="0.0 />
    <point x="0.05" y="0.05" z="0.08 />
</drawcylinder>
<setmkfluid mk="0" />
<fillbox x="0.05 y="0.05" z="0.02" objname="FillBox">
    <modefill>void</modefill>
    <point x="0" y="0" z="0" />
    <size x="0.1" y="0.1" z="0.02" />
</fillbox> 
```

Also, remember to have the fillbox ordered after the creation of the cylinder.

Aaaaand also, I notice yet another bug that will be fixed in a few minutes :)
