### ISSUE TITLE
The problem about the linear motion from a file

### ISSUE THREAD

**Issue by wangjinge1985** [DualSPHysics/DesignSPHysics#41]
Thanks for sharing DesignSPHysics. I am now trying to use the “linear motion from a file” function to determine the movement of a sliding mass, but I cannot change any parameters in the setting window, every parameters keep as 0. Is there any introduction or examples about how to use the “linear motion from a file”?

**Comment by zlotny** [comment]
I've tested this (I also saw your email but I prefer to keep this in here for future reference) and it is a bug on the code. In other types of movement that does not happen.

I'm checking why this is happening and will update DesignSPHysics in a few minutes

**Comment by zlotny** [comment]
It's fixed now.

About an example to use linear motion from a file: In the DualSPHysics package you can find in examples/motion/ the case Motion8, which uses \<mvfile\>. In DesignSPHysics it is basically the same, but you enter the values in the graphical interface instead of writing them on the XML directly.

Closing this as it is fixed now. Thanks for spotting the issue! :)
