### ISSUE TITLE
Follow up the problem of “linear motion from a file”

### ISSUE THREAD

**Issue by wangjinge1985** [DualSPHysics/DesignSPHysics#42]
Hi, Zlotny. I have tried the new version 2001-16-4. The Macro cannot be executed if I download from https://github.com/DualSPHysics/DesignSPHysics and install manually. But it can work after I update it in FreeCAD. After I tried the “linear motion from a file” again, the parameters in the setting windows can be changed and the X Y position moving correct, but the Z position of the model didn’t move. I have compared the XML file of my model with the example, I found the fieldz=”3” is not appear although I have set it in the interface (see below).

<motion>
<objreal ref="0">
<begin mov="1" start="0"/> 
<mvfile id="1" duration="3.0">
<file name="move.txt" fields="4" fieldtime="0" fieldx="1" fieldy="2" />
</mvfile>

**Comment by zlotny** [comment]
Hi there!

About downloading the version manually, I had that happening to a colleague and the issue was basically that FreeCAD was not using the newly downloaded libraries, but the older ones from some sort of a cache. The solution was to delete the FreeCAD folder on %appdata% (In Windows) or /home/$USER/.FreeCAD on GNU/Linux.

About the fieldz problem, you're right! I probably was using the 2D templates while doing some work on the application and doing so the fieldz value slipped out in some way. I've added it back in on commit 41e406bdc6bfed169423788eba2eeaf502d60317.

Please update DesignSPHysics and it should be fixed. Closing the thread.

If you keep to have problems executing the macro please open the Report View (View -> Panels -> Report View) and execute it, so yo may see the error it gives to you. Please open a new issue with that.

Thanks for contributing!
