### ISSUE TITLE
Mooring lines below the boundary particles

### ISSUE THREAD

**Issue by moroth89** [DualSPHysics/DesignSPHysics#46]
Hello, 
Is there any problem with the function of the mooring line, because I have seen in the post-processing that the lines are below the boundary particles.

![Mooring](https://user-images.githubusercontent.com/59596749/72798074-da9fcc80-3c74-11ea-8f9d-8783b9021df0.PNG) 

Is there a way to determine a min value for the z-axes?

DesignPhysics vers.: 0.6.0.2001-20-4

Thank you very much in advance. 

Kind regards 

Moritz

**Comment by zlotny** [comment]
Hi there.

This issue seems to relate more to DualSPHysics than DesignSPHysics, as the problem would persist even without using the GUI, so I'm not able to help you in this.

However I asked my colleague Iván that is developing the MoorDyn integration in DualSPHysics and he suggested that the Water Depth may be wrong. Did you try to increase it a bit? 

If you keep having problems with that please put an issue on https://github.com/DualSPHysics/DualSPHysics as they probably have more knowledge on why that particular issue is present.

**Comment by zlotny** [comment]
Closing this as it has not been active for like a week.

Remember that moorings integration is not yet documented on the DualSPHysics package (and in active development!) and has a lot of limitations right now.

Also, I think you need to ensure the free surface of the fluid is exactly at z=0 due to MoorDyn restrictions.

**Comment by moroth89** [comment]
Hello, thank you very much for your quick reply and apologies for my absence.

I have tried different settings, but the mooring lines are still below the z=0 limit. 

Did I understand correctly that the fluid starts at z=0 and goes up to a certain value? 
Because the mooring lines are still below z=0. 

I will open a new issue at DualSPHysics for this. 
Thanks anyway for your answers.

**Comment by zlotny** [comment]
I don't know very well the restrictions and how to configure MoorDyn to work correctly, so I'm not the best person to ask.

About the fluid, I understood that you have to have the free surface of the fluid exactly on Z=0. So if your fluid is a box with a height of 1 meter, the fluid should go from z=-1 to z=0 exactly. And then in the moorings configuration the water depth should be exactly 1.0

However, the DualSPHysics repo or the forums (forums.dual.sphysics.org) are a better place to ask.

The team is already trying to integrate MoorDyn more into DualSPHysics so it's easy to understand and configure.
