### ISSUE TITLE
FC Case limits not automatically fed to SPH sim

### ISSUE THREAD

**Issue by EEJGH** [DualSPHysics/DesignSPHysics#49]
Hello,

First of all, I am fairly new so I do not know if this is the best way of communicating these kind of things...

I just managed to begin running and I am trying to reproduce the yt tutorial DualSPHysics How to set up and run: [Floating Sphere](https://youtu.be/xZyEG5jLPIg). There are some minor differences between the DesignSPH shown in the videos and the current one, but nothing major usability wise.

What I did spot as a troubling point is that if you run everything "out of the box" with the latest FreeCAD (0.18.4) and DesignSPH 0.6.0.2001-20-4 there is a major probelm in the way SPH is fed, via xml inputs, of its intended case limits.

DesignSPHysics leaves for the case limits in the xml file as default value the string "default" (for the 6 combinations xyz, min, max). This is understood by SPHysics as the volume covered by the particles, on creation. Hence as soon as the floating boundary particles of the tutorial´s sphere breach the initial water level, SPH throws an error claiming that a (floating) boundary was excluded.

As a newby I had to identify the problem and find the issue, what I did then was to manuallly define the Simulation domain in such a way that this would not happen. I did this manually typing information in the "Execution Parameters -> Simulation domain -> 6x Value" which I had already defined in the FreeCAD "Case Limits" object, I guess this is not the most optimal approach...

I wonder whether:
a) The current behavior is the expected one (ignoring the FC Case Limits definition and risking this boundary excluion)
b) It is not the expected behavior due to missing feature / bug on expected feature
c) I am missing some sort of configuration to redefine what that default value should be so that the SPH sim is fed with the FC Cse Limits information...

Best regards!
Eduardo

**Comment by zlotny** [comment]
Hi there! Thanks for taking your time to comment on this.

So this is a bit tricky, because of different interest on the UI usability and how it is perceived, by me and my colleagues.

Technically, the Case Limits objects represents what are the boundaries of GenCase, not DualSPHysics. DualSPHysics doesn't have any knowledge whatsoever of what the case limits are and only cares about the domain of the simulation defined by the volume of the particles feeded to it by the binary data.

Is this easy to understand to beginners? No. Is this straightforward while seeing your case limits are enough to simulate? No. Does this promote usability? No.

Is this the expected behaviour?... Yes.

While I don't personally agree, the GUI is being created exclusively to get people working later on the XML files and CLI environments, so my colleagues here at the lab really want to make sure the same restrictions, steps and hustles are applied in both the GUI as they are in the CLI. That's one of the reasons why now you can't "Save + Gencase" anymore.

I don't quite agree with this approach but I'm not the one to take decisions on this respect. However I have marked a milestone in which the GUI would be "feature complete" (kind of) and then me and the rest of the team will decide how to improve usability and how to steer this software purpose and meaning.

So, summarizing. The case limits are only meant to slice and dimension things in the pre-processing stage, and the user must be responsible of knowing that dualsphysics, then, defines the limits based on the created particles volume.

I hope I can improve this later in the development, and I really understand (and feel) your concern.

PS: I believe when that video was made DualSPHysics automagically added some percentage to the Z+ boundary limits. That was removed once it allowed the user to custom define those values with the Simulation Domain option.

**Comment by zlotny** [comment]
I commented this with my colleagues and we will decide on this particular issue a bit because you're not the only one that had this kind of problem/question.

So at least for things like this we could force Simulation Domain == Case Limits to help people understand better what they're designing.

However this also arises the problem of then knowing that the case limits should be exactly in the edge of the fluid for periodicity to work and so on.

We'll have a look. Thanks for your concern!

**Comment by EEJGH** [comment]
All clear now... A pity the tutorial did not mention anything about the automagical Z margin... The X, Y boundary for periodicity constrain is clear.

Cheers!
