### ISSUE TITLE
Save and Execution problems

### ISSUE THREAD

**Issue by luizfuchs** [DualSPHysics/DesignSPHysics#60]
Hello,

I have updated my DesingSPHysics at 19/02/2020 (a few minutes ago) to continue the execution of a model.

When I opened it, the software aware of the old version of my model, as usual, but every save (even save as) or case run are not working properly and showing the waring as follows:

"
DesignSPHysics version: 0.6.0.2002-19-5
Platform: Windows-8.1-6.3.9600
FreeCAD Version: 0.18.4 (GitTag)
Exception type: <class 'AttributeError'>
Exception value: 'MKBasedProperties' object has no attribute 'property'
Traceback:

  File "C:\Users\luiz.fuchs\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_pre_processing_widget.py", line 206, in on_execute_gencase
    self.on_save_case()
  File "C:\Users\luiz.fuchs\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_pre_processing_widget.py", line 195, in on_save_case
    save_case(save_name, Case.the())
  File "C:\Users\luiz.fuchs\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\file_tools.py", line 262, in save_case
    XMLExporter().save_to_disk(save_name, case)
  File "C:\Users\luiz.fuchs\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\xml\xml_exporter.py", line 107, in save_to_disk
    file.write(self.generate_material(case))
  File "C:\Users\luiz.fuchs\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\xml\xml_exporter.py", line 95, in generate_material
    if mkbasedproperty.property:
"

Thank you very much for your support!

P.S.: Mooring Lines are not presented on "Special" Menu

**Comment by zlotny** [comment]
Hi there:
### About the error
We're constantly adding new features that break disk saves or cases that don't have them present, that's why the error states:
![image](https://user-images.githubusercontent.com/6155245/74914860-70895d00-53c3-11ea-881e-b9033cd62fec.png)

So if you want to continue with a case saved with a previous version please keep using that one until you finish, or if you must continue with a new version you'll need to re-do it again.

Until we reach a "feature complete" release version of DesignSPHysics we're not focusing on backwards compatibility as it would be a a time draining process and we would be fighting against how Python objects and Pickle works internally to achieve that. In the future we'll try to ensure a method of ensuring compatibility each time a version changes.

About your particular error, basically with the version that you have we didn't support properties + materials yet, needed for CHRONO to compute solid-solid interactions correctly. As your case lacks that "property" attribute for an MK DesignSPHyiscs does not understand how to save your case to disk.

### About the mooring lines
We released DesignSPHysics with the MoorDyn+ integration as an experimental feature a few weeks ago to test in different course. However that feature is not yet ready for use as the team is working on it to integrate it better yet. DesignSPHyiscs now detects if your DualSPHysics executable supports Moorings and if that's the case it displays that option on the Special Menu.

As you can see here the very last release of DualSPHysics (on https://github.com/DualSPHysics/DualSPHysics) does not support MoorDyn coupilng, so the GUI just hides it.

If you want to use moorings you'll need to provide a supported DualSPHysics executable in the Setup Plugin window.


So I'm closing this because backwards compatibility is expected but on the (I hope) not so distant future and the Moorings disappearing is just because DualSPHysics does not support it as of right now, it was just a few (buggy) builds before that had that. We need to wait until the DualSPHyiscs team releases DualSPHysics 4.5 (5.0? don't know what's next) to DesignSPHysics to show that feature again.
