### ISSUE TITLE
Problem with 'Linear motion from a file'

### ISSUE THREAD

**Issue by jpd03c** [DualSPHysics/DesignSPHysics#68]
I am trying to complete the main example problem 07_WavemakerFile. I am following the youtube instructions: https://www.youtube.com/watch?v=ngCaODc0378

I get the following error:

*** ERROR: Some boundary particle was excluded. ***
TimeStep: 0.000998  (Nstep: 4)
Total boundary: 4  (fixed=0  moving=4  floating=0)
Excluded for: position=4  rhop=0  velocity=0
Some boundary particle exceeded the +Z limit (top limit) of the simulation domain.
 

*** Exception (JSphGpuSingle::AbortBoundOut)
Text: Fixed, moving or floating particles were excluded. Check VTK file Error_BoundaryOut.vtk with excluded particles.

Finished execution (code=1).
***************************************

It runs normally if I use movement or a wave generator

**Comment by zlotny** [comment]
This doesn't seem a bug, issue or feature request with DesignSPHysics. That video you're following has a few years and a bunch of things changed on DualSPHysics.

Your problem sounds like you haven't extended the Z limit of the simulation domain. You can do it on Execution Parameters -> Simulation Domain (at the bottom). -> Enable and change maximum position on Z to something to +30% and see what happens.

If you believe the error you're getting is due to a bug with this application please specify version, a zip file with your case folder and a way to replicate the problem.
