### ISSUE TITLE
Error During Execution

### ISSUE THREAD

**Issue by ingvibes** [DualSPHysics/DesignSPHysics#70]
Hi. 

I have created the dam-case-project by [this ](https://design.sphysics.org/wiki/doku.php?id=dam-break-example) tutorial. The initial state (box and fluid) is easily exported to ParaView, but when I try to run the case in the "simulation control pannel" of FreeCAD, I get the following error:

![image](https://user-images.githubusercontent.com/54776681/79430263-f6431680-7fc8-11ea-8222-9307b43ff267.png)
 
With the details: 
"An error occurred during execution. Make sure that parameters exist and are properly defined. You can also check your execution device (update the driver of your GPU). Read the details for more information."

The following info might be relevant for the error: 
- I am trying to run it on the CPU, and get an error message concerning GPU. 
- I'm using FreeCAD 0.17

**Comment by zlotny** [comment]
Well there's a lot of weird things going on here. 

First of all I assume you're using a super old version of DesignSPHysics, as FreeCAD 0.17 is also very old and is not supported anymore. DesignSPHysics should fail to start at the moment it detects the FreeCAD version is not 0.18 or greater.

The other thing that bugs me is... where did you find a like to that wiki? It is discontinued and I abandoned it like a few years ago, in 2018. I apparently have missing some link. Those examples and cases are for versions from more than 2 years ago. Lot of things changed since then.

So first of all I have to ask you to use a current version both of FreeCAD (I see you're running Windows, just install a new one downloading it from the webpage) and a new DesignSPHysics (install it following the installation instructions, in here: https://github.com/DualSPHysics/DesignSPHysics#installing-a-release-version)

The interface changed quite a bit but you could try to follow that tutorial. If you keep having problems, please understand that the error you pasted here does not help in nothing, as it says clearly to read the details for more information, which is what we would need to see what really happened, not just that "an error happened".

**Comment by ingvibes** [comment]
Hi, and thanks for answering. 

The reason why I'm using freeCAD 0.17 is that I couldn't get freeCAD 0.18 to work. The problem was to upload the Macro. I have tried both methods of the [DesignSPHysics wiki page](https://github.com/DualSPHysics/DesignSPHysics#installation-instructions), but none of them worked. I started googling it, and people recommended to use the older version with the .py macro. I would be glad to use the newest version if I would be able to download the right macro.

The tutorial was found by just googling "designsphysics dam break case": 
![image](https://user-images.githubusercontent.com/54776681/79453743-631ad880-7fea-11ea-8d16-244e5f8677bf.png)

Update: I have now managed to run another "tutorial-youtube-case" with freeCAD 0.17.  
Sorry for giving you the wrong error-feedback. I've never asked for help before, and pretty new to the programming-community.

**Comment by zlotny** [comment]
Oh I see, it's still indexed on Google. 

To get the latest version working with FreeCAD 0.18 you probably can just delete everything FreeCAD related and install the new version. This is a bit tricky because each case is a bit different.

However if you:
1. Uninstall FreeCAD
2. Delete the folder _FreeCAD_ inside C:/Users/youruser/AppData/Roaming
3. Install FreeCAD 0.18
4. Open FreeCAD, then the Addon Manager and Download DesignSPHyiscs, just like in the instructions you linked.
5. Try to run DesignSPHysics from the Addon Manager.

I don't recommend to use old versions because they had a lot of bugs and missing features, and also they used old versions of DualSPHysics, with also bugs and missing features. Also if you have any problem with that I won't be able to help as I cannot fix an older release.

Thanks for using DesignSPHysics, though. I'll try to find an easier way to troubleshoot installation issues.

**Comment by ingvibes** [comment]
Thanks for the tip. I'll try it. 

One more question tho, because the first thing I tried (in freeCAD 0.18, before installing freeCAD 0.17) was to install DesignSPHysics from the Addon Manager. But I couldn't find the macro in: macro--> macros --> addons --> macros. But it existed in -->addons-->WorkBenches, thus this was the one I installed. See the picture for what I installed: 
![image](https://user-images.githubusercontent.com/54776681/79484578-27950400-8014-11ea-9ac6-3e05c43c3fd9.png)

**Comment by zlotny** [comment]
That's the one you should install, yes. The person responsible for the Addon Manager listing put my Macro into the workbenches list, I assume because is a big dock with a lot of tools, more than a macro, but it's bootstrapped as one.

**Comment by ingvibes** [comment]
Hi,

Quick question here, hope it’s ok that I ask:
Is it possible to use a Bingham fluid model in DesignSPHysics? I can only find the choices: “artificial” and “Laminar+SPS”. Thus, I wondered if it was a way to set the parameter keys HB_parameter_0 or HB_Papanastasiou_0?

Also, does there exist a Q&A forum for DesigSPHysics?

Best regards,
Ingvibes

**Comment by zlotny** [comment]
Hi there, don't worry, you can ask in here.

I didn't implement any of those options on DesignSPHyiscs. In fact it's the first time I heard about them :sweat_smile: 

I'm afraid the only way to use those options (at least for now) it's to design the cases directly on the XML and run them with the command line tools.

About a forum, yes, you can ask questions on forums.dual.sphysics.org

Hope that helps. By the way I'm closing this issue now as it seems resolved.

**Comment by ingvibes** [comment]
Hi and thanks for the answers!

That’s fine. Btw, it worked to install the macros in freeCAD 0.18 the second time, so thanks for the tips 😊


________________________________
Fra: Andrés Vieira <notifications@github.com>
Sendt: Monday, April 20, 2020 12:40:56 PM
Til: DualSPHysics/DesignSPHysics <DesignSPHysics@noreply.github.com>
Kopi: ingvibes <ingvibes@stud.ntnu.no>; Author <author@noreply.github.com>
Emne: Re: [DualSPHysics/DesignSPHysics] Error During Execution (#70)


Hi there, don't worry, you can ask in here.

I didn't implement any of those options on DesignSPHyiscs. In fact it's the first time I heard about them 😅

I'm afraid the only way to use those options (at least for now) it's to design the cases directly on the XML and run them with the command line tools.

About a forum, yes, you can ask questions on forums.dual.sphysics.org

Hope that helps. By the way I'm closing this issue now as it seems resolved.
