### ISSUE TITLE
large vorticity close to the walls

### ISSUE THREAD

**Issue by AtefeFz** [DualSPHysics/DesignSPHysics#86]
Hello,

I am modeling a mixing flow using Dualsphysics and the early results I have,  show a very large vorticity field along the wall. Considering that the velocity of the walls is zero and the flow has a velocity of around 0.5 m/s this vorticity is expected, I guess. Am I right? 
As the experiment is a large flume without the effect of a wall, I do not want the wall vorticity affect my results in the mixing area. apart from widening the setup geometry which results in computational cost, is there any way that I can avoid large vorticity along the wall? 

P.S: I have tried posting my question on the forum but there was no option for me to submit any. I already signed up there. Could you please let me know how can I post my question on the forum? https://forums.dual.sphysics.org/categories/dualsphysics-v5-0

![Screen Shot 01-21-21 at 07 51 PM](https://user-images.githubusercontent.com/67873134/105642416-8d41d680-5e57-11eb-8184-9662c7151ac3.PNG)

**Comment by zlotny** [comment]
This issue is already present in https://github.com/DualSPHysics/DualSPHysics/issues/78 which a better place to ask.

About the forum issue, assuming you signed up and confirmed your email, just navigate to the appropriate category (at the right of the page) and press "New Discussion". If you can't see that maybe the email isn't confirmed. I confirmed the email of users with your name (AtefeFz) so you should be good to go.
