### ISSUE TITLE
Issue manual loading DesignSPHysics to FreeCAD 0.18

### ISSUE THREAD

**Issue by yzhao469** [DualSPHysics/DesignSPHysics#87]
I downloaded the DesignSPHysics code from "https://github.com/DualSPHysics/DesignSPHysics#installation-instructions" and tried to load it following the "Installing a development build" instruction, however there is a error reported from FreeCAD 0.18: 

Traceback (most recent call last):
  File "C:/Program Files/FreeCAD 0.18/Macro/DesignSPHysics.FCMacro", line 15, in <module>
    from mod.widgets.error_report_dialog import ErrorReportDialog  # pylint: disable=wrong-import-position
  File "C:\Program Files\FreeCAD 0.18\Mod\DesignSPHysics\mod\widgets\error_report_dialog.py", line 13, in <module>
    from mod.constants import VERSION
  File "C:\Program Files\FreeCAD 0.18\Mod\DesignSPHysics\mod\constants.py", line 6, in <module>
    from mod.enums import FreeCADObjectType
  File "C:\Program Files\FreeCAD 0.18\Mod\DesignSPHysics\mod\enums.py", line 235, in <module>
    class HelpText:
  File "C:\Program Files\FreeCAD 0.18\Mod\DesignSPHysics\mod\enums.py", line 279, in HelpText
    YINCREMENTX = __("")
  File "C:\Program Files\FreeCAD 0.18\Mod\DesignSPHysics\mod\translation_tools.py", line 35, in __
    with open(filename, "w", encoding="utf-8") as f:
<class 'PermissionError'>: [Errno 13] Permission denied: 'C:\\Program Files\\FreeCAD 0.18\\Mod\\DesignSPHysics\\mod/lang/english.json'

Could anyone please help me how to solve this issue? I tried to follow "installing a release version" instruction first, but it also failed: when I go to "Macros addones" GUI, it takes forever to "retrieving info from wiki". The error says "unable to fetch the code of this macro".

Thank you!

**Comment by zlotny** [comment]
Hi there. Installing directly from FreeCAD is known to have some problems and be slow. I'm hoping the FreeCAD team fixes that in further releases of FreeCAD.

About the manual installation (from a development build), the error that you have is that basically you installed it in the wrong directory. From the readme that you pointed out:

> **By default, for example, in Windows, it is located in %appdata%/FreeCAD/Mod** or in Linux in ~/.FreeCAD/Mod

AppData on windows is not the same as C:\Program Files\. AppData is meant to have user permission and control while Program Files is administrator-level only, thus, the issue you're having. As the error states:

> <class 'PermissionError'>: [Errno 13] Permission denied: 'C:\Program Files\FreeCAD 0.18\Mod\DesignSPHysics\mod/lang/english.json'

DesignSPHyiscs does not have permissions to read/write appropriately in that file. That's why it fails.

To fix it you'll have to install it as the installation instructions state, in AppData. If you are not familiar with using variables in MS Windows, you can find manually where AppData is searching for it on the Internet. This is the first hit for me: https://www.howtogeek.com/318177/what-is-the-appdata-folder-in-windows/

Also, please delete the macro you installed on C:\Program Files\FreeCAD 0.18. FreeCAD does not like to have replicated the same thing in 2 equal directories and it surely will lead to errors.


Hope this helped.

**Comment by yzhao469** [comment]
Thank you for the prompt response. It does help!

Regards,
Yumeng

**Comment by BOUKR** [comment]
I downloaded the DesignSPHysics code from "https://github.com/DualSPHysics/DesignSPHysics#installation-instructions" and i  follow the "Installing a development build" instructions, using FreeCAD 0.18, the installation its done but when i clic in Macro i see only "DesignSPHysics.FCMacro".  "DesignSPHysics.py" its not in the list !!!!.
I do not know, if i need it necessary or i can excute juste "DesignSPHysics.FCMacro" ???.

Could anyone please help me how to solve this issue ?

**Comment by zlotny** [comment]
Hi @BOUKR , the DesignSPHysics.FCMacro file is the new equivalent to DesignSPHysics.py. Just execute that, as it is the same.

If you have more problems related with this please open a new issue. Closing this one as it seems solved

**Comment by BOUKR** [comment]
it's done. thank you so much.
